---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data
```{r}
setwd("C:/Users/Luke/Desktop/Johns Hopkins Data Science/Reproducible Research/Week 1")
library(knitr)
unzip("repdata-data-activity.zip")
raw <- read.csv("activity.csv", header = TRUE, sep = ",")
library(lubridate)
raw$date <-ymd(raw$date)
```

## What is mean total number of steps taken per day?
```{r hist}
na <- raw[is.na(raw)]
dailysteps <- tapply(raw$steps, raw$date, sum, na.rm = TRUE)
dailysteps <- dailysteps[!is.na(dailysteps)]
hist(dailysteps, xlab= "Steps per day", main= "Step Histogram",
     breaks = 24, col= "steel blue")
mean_steps <- mean(dailysteps)
median_steps <- median(dailysteps)
```

## What is the average daily activity pattern?
```{r}
mean_int <- tapply(raw$steps, raw$interval, mean, na.rm=TRUE)
plot(mean_int, type = "l", xlab= "Time Interval", 
     ylab= "Average Steps", main = "Time Series Plot of Steps")
max <- max(mean_int)
match(max, mean_int)
mean_int[104]
```
835 interval has max steps of 206.1698


## Imputing missing values
```{r}
sum(is.na(raw)) 
raw_not_imputed <- raw
na <- is.na(raw$steps)

mean_int <- tapply(raw$steps, raw$interval, mean, na.rm=TRUE) 
raw$steps[na]<- mean_int[as.character(raw$interval[na])]
sum(is.na(raw$steps)) 
imputed_dailysteps<-tapply(raw$steps, raw$date, sum, na.rm = TRUE)
hist(imputed_dailysteps, col = "red", 
     xlab = "Daily Steps", main = "Imputed Daily Steps Histogram")
mean_imputed_steps <- mean(imputed_dailysteps)
median_imputed_steps <- median(imputed_dailysteps)
```
2304 number of NA

## Are there differences in activity patterns between weekdays and weekends?
```{r}
raw$type <- ifelse(weekdays(raw$date)== "Saturday" 
            | weekdays(raw$date) == "Sunday", "weekend", "weekday")
head(raw)
library(lattice)
mean_by_int <- tapply(raw$steps, list(raw$interval, raw$type),mean)
library(reshape2)
mean_by_int <-melt(mean_by_int)
colnames(mean_by_int) <- c("interval", "type", "steps")
xyplot(steps ~ interval | type, data = mean_by_int, 
       layout = c(1,2), type = "l", main = "Average Steps", 
       xlab = "Interval", ylab = "Steps")
```